### PR TITLE
Home picture

### PR DESCRIPTION
**Pull request by danielkg123**
migration add picture to users
add picture to assets/mahasiswa
change index home to fit image
fix seeder

### CODE REVIEW

**Comment by FlyingLemonade** [comment]
1. Server assets foldering design need to be more tidy 
2. duplicated image found
3. try to store the image by its category like foods, logo, kantin, user, etc
4. Please set the name of the picture to a uid so we can call it in the blade using its id
(you may use another aproach but please be wise about the usage of the database memory)
4. Dont put things(assets) that you want to call outside public file

**Review by FlyingLemonade — CHANGES_REQUESTED** [review]
1. Server assets foldering design need to be more tidy 
2. duplicated image found
3. try to store the image by its category like foods, logo, kantin, user, etc
4. Please set the name of the picture to a uid so we can call it in the blade using its id
(you may use another aproach but please be wise about the usage of the database memory)
5. Dont put things(assets) that you want to call outside public file
 Ganbatte xd

**Comment by danielkg123** [comment]
> 1. Server assets foldering design need to be more tidy
> 2. duplicated image found
> 3. try to store the image by its category like foods, logo, kantin, user, etc
> 4. Please set the name of the picture to a uid so we can call it in the blade using its id
>    (you may use another aproach but please be wise about the usage of the database memory)
> 5. Dont put things(assets) that you want to call outside public file
>    Ganbatte xd

i tried to create a new folder for profile
but i cant call it on the page idk why, when i put it on mahasiswa/profile
but when i put it in mahasiswa it runs fine

**Comment by danielkg123** [comment]
> > 1. Server assets foldering design need to be more tidy
> > 2. duplicated image found
> > 3. try to store the image by its category like foods, logo, kantin, user, etc
> > 4. Please set the name of the picture to a uid so we can call it in the blade using its id
> >    (you may use another aproach but please be wise about the usage of the database memory)
> > 5. Dont put things(assets) that you want to call outside public file
> >    Ganbatte xd
> 
> i tried to create a new folder for profile but i cant call it on the page idk why, when i put it on mahasiswa/profile but when i put it in mahasiswa it runs fine

and to add to this the dupe image doesnt matter since github uses metadata to detect the location of the file so it'll just replace it when  u merge on main

**Comment by FlyingLemonade** [comment]
I think you misunderstand what i mean, what i mean by duplicate picture is there are 2 pictures in diffrent
file path like kantin p in home file and KantinP.jpg in mahasiswa file both are actually the same file 
we can just put it in a file and make all the web(html) refer to that folder without using duplicate picture.
You cant call the profile because your assets file is outside of public folder, you need to put it inside
public folder to call all assets you want to use.

**Pull request closed without merging**
